"""empty message

Revision ID: e39cb798de07
Revises: ef6481bbc059
Create Date: 2022-08-08 17:19:06.067547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39cb798de07'
down_revision = 'ef6481bbc059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avito_request_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avito_request_id'], ['avito_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_values_id'), 'request_values', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_values_id'), table_name='request_values')
    op.drop_table('request_values')
    # ### end Alembic commands ###
