"""empty message

Revision ID: e84c94b788b5
Revises: f7eb096deda2
Create Date: 2022-08-09 12:36:04.027444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84c94b788b5'
down_revision = 'f7eb096deda2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avito_requests', sa.Column('query', sa.String(length=255), nullable=True))
    op.drop_column('avito_requests', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avito_requests', sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('avito_requests', 'query')
    # ### end Alembic commands ###
