"""empty message

Revision ID: f7eb096deda2
Revises: e39cb798de07
Create Date: 2022-08-09 12:26:39.033990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7eb096deda2'
down_revision = 'e39cb798de07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_values', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('request_values', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_values', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('request_values', 'timestamp')
    # ### end Alembic commands ###
