"""empty message

Revision ID: 60700a266b06
Revises: 
Create Date: 2022-08-10 12:36:22.078742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60700a266b06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avito_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avito_queries_id'), 'avito_queries', ['id'], unique=True)
    op.create_table('avito_query_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avito_query_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avito_query_id'], ['avito_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avito_query_values_id'), 'avito_query_values', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avito_query_values_id'), table_name='avito_query_values')
    op.drop_table('avito_query_values')
    op.drop_index(op.f('ix_avito_queries_id'), table_name='avito_queries')
    op.drop_table('avito_queries')
    # ### end Alembic commands ###
